<a href="https://colab.research.google.com/github/KARTIKPARATKAR/MACHINE-LEARNING-WORK/blob/main/MatrixInMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import numpy as np

In [77]:
#In machine learning we ofter deal with datasets. It can contain 100s of rows and 10s of columns.
#This dataset having multiple rows and column can be considered as matrix.
#All the processing and computation operations happening in ML is like matrix operations only.

Creating matrix using numpy

In [78]:
mat1=np.array([[2,3,6],[4,5,0]])
print(mat1)

[[2 3 6]
 [4 5 0]]


In [79]:
mat1.shape   #Matrix has a shape of (2,3) It means 2 rows and 2 columns

(2, 3)

Creating matrix with random values

In [80]:
mat2=np.random.rand(3,3) #Matrix with random values having 3*3 size
print(mat2)

[[0.62387637 0.24187931 0.61857789]
 [0.62043078 0.19050376 0.8922325 ]
 [0.70623443 0.76483639 0.44322798]]


In [81]:
mat3=np.random.randint(100,size=(3,4)) #Give random values less than 100. Create a shape of matrix as 3 rows and 4 columns
print(mat3)

[[35 74 32 61]
 [18  9 65 14]
 [47 52 55 26]]


In [82]:
#Matrix with all the values as 1
mat4=np.ones((3,3))
print(mat4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [83]:
mat4=np.ones((3,3),dtype=int)
print(mat4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [84]:
mat4=np.ones((5,5)) #5rows and 5columns
print(mat4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Null Matrix or Zero Matrix

In [85]:
nullmatrix=np.zeros((4,4),dtype=int)
print(nullmatrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Identity matrix: Diagonal values are 1 and all other are zero

In [86]:
identity=np.eye(4,dtype=int)
print(identity)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [87]:
identity5=np.eye(5,dtype=int)
print(identity5)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Transpose-Rows are converted into columns and columns are converted into rows

In [88]:
a=np.random.randint(100,size=(3,4))
print(a)

[[66 62 98 81]
 [95 19 77 32]
 [64 94  2 40]]


In [89]:
transposeofa=np.transpose(a)
print(transposeofa)

[[66 95 64]
 [62 19 94]
 [98 77  2]
 [81 32 40]]
