<a href="https://colab.research.google.com/github/KARTIKPARATKAR/MACHINE-LEARNING-WORK/blob/main/MatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
import numpy as np

Matrix Addition

In [92]:
#Two matrices can only be added when both the column and rows are same. It means shape should be same.
a=np.array([[2,3],[4,5]])
b=np.array([[6,7],[1,2]])
print(a)
print(b)

[[2 3]
 [4 5]]
[[6 7]
 [1 2]]


In [97]:
a.shape

(2, 2)

In [98]:
b.shape

(2, 2)

In [99]:
sum = a+b

In [102]:
print(sum)  #This will print the addition of both the matices

[[ 8 10]
 [ 5  7]]


In [103]:
c=np.random.randint(10,size=(3,3))
d=np.random.randint(20,size=(3,3))
print(c)
print(d)

[[4 0 2]
 [3 3 1]
 [0 4 9]]
[[ 1  9  3]
 [18 15  2]
 [ 6  1  5]]


In [104]:
add=np.add(c,d)
print(add)

[[ 5  9  5]
 [21 18  3]
 [ 6  5 14]]


Matrix Subtraction

In [106]:
p=np.array([[1,2],[3,4]])
q=np.array([[1,4],[2,6]])
sub=p-q
print(sub)

[[ 0 -2]
 [ 1 -2]]


In [107]:
r=np.array([[1,2,3],[4,5,6]])
s=np.array([[0,1,2],[3,4,5]])
sub2=np.subtract(r,s)
print(sub2)

[[1 1 1]
 [1 1 1]]


Multiplying a matrix by scalar

In [111]:
sca=np.random.randint(10,size=(3,3))
z=3
print(sca)
mul=np.multiply(sca,z)
print(mul)

[[1 2 1]
 [5 8 0]
 [5 5 1]]
[[ 3  6  3]
 [15 24  0]
 [15 15  3]]


In [113]:
let=np.array([[1,2,3],[4,5,6]])
print(let)
num=2
pro=let*num
print(pro)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


Multiplication of two matrices

In [122]:
mat1=np.random.randint(5,size=(3,4))
mat2=np.random.randint(5,size=(4,3))
print("Matrix1\n",mat1)
print("Matrix2\n",mat2)

Matrix1
 [[3 2 4 0]
 [0 4 3 4]
 [0 0 4 2]]
Matrix2
 [[3 0 1]
 [3 1 0]
 [4 3 2]
 [1 1 0]]


In [124]:
res=np.dot(mat1,mat2)
print(res)

[[31 14 11]
 [28 17  6]
 [18 14  8]]
