<a href="https://colab.research.google.com/github/KARTIKPARATKAR/MACHINE-LEARNING-WORK/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np


In [39]:
a=np.array([1,2,3,4])

In [40]:
print(a)

[1 2 3 4]


In [41]:
a.shape

(4,)

In [42]:
a.size

4

In [43]:
twod=np.array([[1,2],[3,4],[5,6]])

In [44]:
print(twod)

[[1 2]
 [3 4]
 [5 6]]


In [45]:

twod.shape

(3, 2)

In [46]:
twod.size

6

In [47]:

twod.dtype

dtype('int64')

In [48]:
zero=np.zeros((3,3))

In [49]:
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [50]:
rand=np.ones((2,2))

In [51]:

print(rand)

[[1. 1.]
 [1. 1.]]


In [52]:
print("Indexing in numpy array:")

Indexing in numpy array:


In [53]:
p=np.array([11,22,33,44,55,66,77,88,99])


In [54]:
print(p[1])

22


In [55]:
print(p[2])

33


In [56]:
print(p[3])

44


In [57]:
p[0]=0  #Seting the value at index 0 as 0

In [58]:
print(p)    #Printing the numpy array when array emenet at 0 index is made 0

[ 0 22 33 44 55 66 77 88 99]


In [59]:
t=np.array([[1,2,3,4],[6,7,8,9],[11,22,33,44]])

In [60]:
print(t)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 22 33 44]]


In [61]:
print("0th column of numpy array:",t[:,0])

0th column of numpy array: [ 1  6 11]


In [62]:
print("1st row of numpy array:",t[1,:])

1st row of numpy array: [6 7 8 9]


In [63]:
print(t)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 22 33 44]]


In [64]:
x=np.array([[1,2],[3,4]],dtype=np.float64)

In [65]:
y=np.array([[5,6],[7,8]],dtype=np.float64)

In [66]:
print(x)

[[1. 2.]
 [3. 4.]]


In [67]:
print(y)

[[5. 6.]
 [7. 8.]]


In [68]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [69]:
print(x.min())  #Min element of x

1.0


In [70]:
print(y.max())   #Max element of y

8.0


In [71]:
type(a)   #This will give the type of array

numpy.ndarray

In [72]:
five=np.full([2,2],5)

In [73]:
print(five)

[[5 5]
 [5 5]]


In [74]:
#Creating numpy array with random values
g=np.random.random([3,4])

In [75]:
print(g)

[[0.23287191 0.51270624 0.45494187 0.41768898]
 [0.49434543 0.34098572 0.54330738 0.79091157]
 [0.04875048 0.31286528 0.54065611 0.3565757 ]]


In [76]:
#Converting list to numpy array
list=[11,22,33,44,55,66,77,88]


In [77]:

type(list)

list

In [78]:
arr=np.array(list)

In [79]:
type(arr)

numpy.ndarray

In [80]:

m=np.random.randint(10,100,(4,4))  #Generating numpy array of 4*4 dimensions having numbers between 10 to 100
print(m)

[[64 13 19 45]
 [39 74 65 31]
 [69 68 47 30]
 [73 25 49 89]]


In [81]:
m.shape

(4, 4)

In [82]:

m.ndim  #Knowing the dimension of array

2

In [83]:
m.size  #Size of array

16

In [84]:
m.dtype

dtype('int64')

In [85]:
l1=[1,2,3,4]
l2=[4,5]


In [86]:
print(l1+l2)  #When you use + on python list it

[1, 2, 3, 4, 4, 5]


In [87]:
l1=np.array([1,2,3])
l2=np.array([4,5,6])

In [88]:
print(l1+l2)

[5 7 9]


In [89]:
#Array manupulation

In [90]:
p=np.random.randint(1,100,(2,3))

In [91]:
print(p)

[[63 35 20]
 [96 68 28]]


In [92]:
print(p.shape)

(2, 3)


In [93]:
q=np.transpose(p)

In [94]:
print(q)

[[63 96]
 [35 68]
 [20 28]]


In [95]:
#Reshaping array
r=np.random.randint(10,40,(3,4))

In [96]:
print(r)

[[17 32 30 31]
 [38 21 21 16]
 [19 32 15 36]]


In [97]:
print(r.shape)

(3, 4)


In [98]:
s=r.reshape(4,3)

In [99]:
print(s)

[[17 32 30]
 [31 38 21]
 [21 16 19]
 [32 15 36]]


In [100]:
print(s.shape)

(4, 3)
